server:
  port: 8081
spring:
datasource:
  url: jdbc:postgresql://localhost:5433/employee
username: postgres
  password: 1273
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      properties.hibernate.format_sql: true
